# Generated by Django 4.2.4 on 2023-09-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='med_metabolites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plant_Id', models.IntegerField()),
                ('Plant_Name', models.TextField()),
                ('General_Metabolites', models.TextField()),
                ('Primary_Metabolites_and_Functions', models.TextField()),
                ('Secondary_Metabolites_and_Functions', models.TextField()),
                ('Common_Metabolites', models.TextField()),
                ('Unique_Metabolites', models.TextField()),
                ('Metabolic_Pathway', models.TextField()),
                ('Structure_of_Metabolites', models.URLField()),
                ('References', models.URLField()),
            ],
        ),
    ]
