# Generated by Django 4.2.4 on 2023-10-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabolites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='med_metabolites',
            name='Common_Metabolites',
        ),
        migrations.AddField(
            model_name='med_metabolites',
            name='kegg_link',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='med_metabolites',
            name='Structure_of_Metabolites',
            field=models.ImageField(upload_to=''),
        ),
    ]
