# Generated by Django 4.2.4 on 2023-10-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabolites', '0002_remove_med_metabolites_common_metabolites_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='med_metabolites',
            old_name='Structure_of_Metabolites',
            new_name='Structure_of_Metabolites_1',
        ),
        migrations.AddField(
            model_name='med_metabolites',
            name='Structure_of_Metabolites_2',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
