# Generated by Django 4.2.4 on 2023-10-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metabolites', '0004_alter_med_metabolites_structure_of_metabolites_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='med_metabolites',
            name='Structure_of_Metabolites_2',
        ),
    ]
