# Generated by Django 4.2.4 on 2023-10-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabolites', '0005_remove_med_metabolites_structure_of_metabolites_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='med_metabolites',
            name='Structure_of_Metabolites_2',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
