# Generated by Django 5.1.1 on 2025-04-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteom', '0002_remove_med_proteom_plant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='med_proteom',
            old_name='Protein_Identical_Group',
            new_name='Identical_Protein_Groups',
        ),
        migrations.AddField(
            model_name='med_proteom',
            name='Protein_Seq',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='med_proteom',
            name='Scientific_Name',
            field=models.TextField(default=''),
        ),
    ]
