# Generated by Django 5.1.1 on 2025-04-05 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='med_class',
            old_name='Class',
            new_name='NCBI_Taxonomy_ID',
        ),
        migrations.RemoveField(
            model_name='med_class',
            name='Division',
        ),
        migrations.RemoveField(
            model_name='med_class',
            name='Kingdom',
        ),
        migrations.RemoveField(
            model_name='med_class',
            name='Plant_Id',
        ),
    ]
