# Generated by Django 5.1.1 on 2025-04-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_rename_class_med_class_ncbi_taxonomy_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='med_class',
            name='NCBI_link',
            field=models.URLField(default=''),
        ),
    ]
