# Generated by Django 4.2.4 on 2024-06-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='med_class',
        ),
    ]
