# Generated by Django 5.1.1 on 2024-11-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='med_phytochem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plant_Name', models.TextField()),
                ('Scientific_Name', models.TextField()),
                ('Phytochemicals', models.TextField()),
                ('Activity_Count', models.IntegerField()),
                ('Formula', models.TextField()),
                ('IUPAC_Name', models.TextField()),
                ('SMILES', models.TextField()),
                ('Plant_Part', models.TextField()),
                ('Molecular_Mass', models.TextField()),
                ('Monoisotopic_Mass', models.TextField()),
                ('LogP', models.TextField()),
                ('Hydrogen_Acceptors', models.TextField()),
                ('Hydrogen_Donors', models.TextField()),
                ('Rotatable_Bond_Count', models.TextField()),
                ('Polar_Surface_Area', models.TextField()),
                ('Structure', models.URLField()),
                ('References', models.URLField()),
            ],
        ),
    ]
