# Generated by Django 5.1.1 on 2024-11-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='med_transcriptom',
            name='Plant_Id',
        ),
    ]
