# Generated by Django 5.1.1 on 2025-04-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptom', '0002_remove_med_transcriptom_plant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='med_transcriptom',
            old_name='Bioproject',
            new_name='BioProject',
        ),
        migrations.RenameField(
            model_name='med_transcriptom',
            old_name='Biosample',
            new_name='BioSample',
        ),
        migrations.AddField(
            model_name='med_transcriptom',
            name='DNA',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='med_transcriptom',
            name='RNA',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='med_transcriptom',
            name='Scientific_Name',
            field=models.TextField(default=''),
        ),
    ]
