# Generated by Django 4.2.4 on 2023-09-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='med_basic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plant_Id', models.IntegerField()),
                ('Plant_Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Parts_Used', models.TextField()),
                ('Weather_Conditions_Required_to_Grow', models.TextField()),
                ('Bioactive_Compound', models.TextField()),
                ('Chemical_Properties', models.TextField()),
                ('Morphological_Features', models.TextField()),
                ('Medicinal_Value', models.TextField()),
                ('States_of_India_Support_their_Growth', models.TextField()),
                ('References', models.URLField()),
            ],
        ),
    ]
