# Generated by Django 4.2.4 on 2024-06-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='med_geno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plant_Id', models.IntegerField()),
                ('Plant_Name', models.TextField()),
                ('Scientific_Name', models.TextField()),
                ('Nucleotide', models.TextField()),
                ('mRNA_Sequence', models.TextField()),
                ('Genome_Sequence', models.TextField()),
                ('NCBI_link', models.URLField()),
            ],
        ),
    ]
