# Generated by Django 5.1.1 on 2025-04-05 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='med_geno',
            name='Plant_Id',
        ),
    ]
