# Generated by Django 4.2.4 on 2023-09-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='med_genomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plant_Id', models.IntegerField()),
                ('Plant_Name', models.TextField()),
                ('Chromosome_Number', models.IntegerField()),
                ('Ploidy', models.TextField()),
                ('Genome_Size', models.IntegerField()),
                ('Nucleotide', models.IntegerField()),
                ('mRNA_Sequence', models.IntegerField()),
                ('Genome_Sequence', models.IntegerField()),
                ('Remark', models.TextField()),
                ('References', models.TextField()),
                ('Literature_Paper_Link', models.URLField()),
            ],
        ),
    ]
