# Generated by Django 4.2.4 on 2023-09-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='med_genomes',
            name='NCBI_link',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='med_genomes',
            name='Genome_Size',
            field=models.TextField(),
        ),
    ]
