# Generated by Django 4.2.4 on 2023-10-01 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0002_med_genomes_ncbi_link_alter_med_genomes_genome_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='med_genomes',
            name='References',
        ),
        migrations.RemoveField(
            model_name='med_genomes',
            name='Remark',
        ),
    ]
