# Generated by Django 4.2.4 on 2023-10-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0003_remove_med_genomes_references_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med_genomes',
            name='Chromosome_Number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='med_genomes',
            name='Genome_Sequence',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='med_genomes',
            name='Nucleotide',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='med_genomes',
            name='mRNA_Sequence',
            field=models.TextField(),
        ),
    ]
